### ISSUE TITLE
Manque de certaines précisions concrètes dans la partie "Quelles données personnelles dois-je retirer de mon jeu de données"

### ISSUE THREAD

**Issue by soizicpenicaud** [etalab-ia/pseudonymisation_decisions_ce#2]
Certaines parties pourraient être précisées pour rendre ce guide plus opérationnel.

Vous indiquez que "Cela dépend du contexte réglementaire, le même cadre ne s'appliquant pas à tous les documents. "
=> A qui s'adresser/où regarder pour connaître ce contexte réglementaire ? 

Vous dites que "retirer trop de catégories d'informations reviendrait à perdre beaucoup d'informations et appauvrirait le contenu d'une décision."
=> Pourquoi ? est-ce que vous avez un exemple concret ? 

Vous dites "Il y a donc un arbitrage à faire entre la minimisation du risque de réidentification et la préservation de l'utilité des données."
=> Qui doit faire cet arbitrage, concrètement ? Comment ? quelles compétences (juridiques, techniques...)

**Comment by jdenes** [comment]
Reste à répondre à la première remarque !

**Comment by jdenes** [comment]
Précisions sur le contexte réglementaire ajoutées
