### ISSUE TITLE
Partie 1 - Quelles données personnelles dois-je retirer ? 

### ISSUE THREAD

**Issue by KimMontalibet** [etalab-ia/pseudonymisation_decisions_ce#23]
Il me semble qu'il faut aussi parler des cas d'usages des données pour faire le choix des éléments à retirer en fonction de leur utilité. 

Trouver le bon curseur n'est pas simple et doit passer par une double analyse des risques de réidentification, à la fois **juridique** (pour évaluer par exemple quelles données ne doivent pas pouvoir être réidentifiées) et **technique** (pour estimer la possibilité technique de réidentifier ces données). Juger de l'utilité de conserver ou non certaines catégories de données dépendra aussi des usages envisagés de ces données.

**Comment by jdenes** [comment]
Bien vu !!
