### ISSUE TITLE
Reprendre les catégories de la partie 2 dans la partie 3

### ISSUE THREAD

**Issue by soizicpenicaud** [etalab-ia/pseudonymisation_decisions_ce#8]
En l'état, certaines catégories de la partie 2 (qui est très claire) apparaissent dans la partie 3 qui sert à illustrer, mais pas toutes. Je pense notamment à "organiser ses données". 
"Apprentissage" remplace "Entraîner son modèle" => peut-être reprendre le même terme pour garder de la cohérence.

**Comment by jdenes** [comment]
Les publics sont légèrement différents, je pense qu'on ne fera pas mieux qu'en l'état. Je ferme donc l'issue
