### ISSUE TITLE
Déplacer "Quelles ressources disponibles pour pseudonymiser" ?

### ISSUE THREAD

**Issue by soizicpenicaud** [etalab-ia/pseudonymisation_decisions_ce#9]
Ici, je ne suis pas sûre, mais je trouve que les ressources disponibles (à présent à la toute fin de la partie 3) pourraient venir plus tôt dans le guide, par exemple dans la partie 2, qui est la partie plus "théorie / outillage" alors que la partie 3 est la partie d'illustration. Elles pourraient ensuite être reprises dans la partie 3 si besoin.

**Comment by jdenes** [comment]
Bonne idée ! Je les ai plutôt mises dans la partie 1, qui fait beaucoup références à ces ressources, mais pas la partie 2.
